var marco = document.getElementById('marco');
var estilo_de_marco = marco.getContext('2d');
estilo_de_marco.shadowOffsetX=-10;
estilo_de_marco.shadowOffsetY=5;
estilo_de_marco.shadowBlur=5;
estilo_de_marco.shadowColor="rgba(0, 0, 255, 0.5)";
estilo_de_marco.shadowOffsetX=5;
estilo_de_marco.moveTo(80,10);
estilo_de_marco.lineTo(1350,10);
estilo_de_marco.strokeStyle = "#2866BB";
estilo_de_marco.moveTo(1350,10);
estilo_de_marco.lineTo(1350,710);
estilo_de_marco.moveTo(1350,710);
estilo_de_marco.lineTo(80,710);
estilo_de_marco.moveTo(80,710);
estilo_de_marco.lineTo(80,10);
estilo_de_marco.lineWidth=15;
estilo_de_marco.lineCap="round";
estilo_de_marco.stroke();